### ISSUE TITLE
GT_ReadAddress dont work in v1.4

### ISSUE THREAD

**Issue by BillCipher-exe** [haseeb-heaven/GTLibc#1]
it seem that GT_ReadAddress() dosent get the right value to the memory address. in v1.3 it works fine.

**Comment by haseeb-heaven** [comment]
Now in V 1.4 all method works for generic data like **int,float,char etc** and **GT_ReadAddress()** method now returns **LPVOID** instead of **DWORD** so you need to cast in now to get the exact value.

See below example.

    DWORD pistol_value = GT_ReadAddress(weapon_base_address); //GTLibc V 1.3 . No casting required
    DWORD pistol_value = *(PDWORD)GT_ReadAddress(weapon_base_address); //GTLibc V 1.4 Casting required because of generic data.

The same thing applies for **GT_WriteAddress()** as well.

    DWORD unlimited_money = 0x7FFFFFFFUL;
    BOOL write_status = GT_WriteAddress(money_address,unlimited_money); //GTLibc V 1.3 pass variable to write.
    BOOL write_status = GT_WriteAddress(money_address,&unlimited_money); //GTLibc V 1.4 pass address of variable to write
