### ISSUE TITLE
error: the expression must be a pointer to a complete object type

### ISSUE THREAD

**Issue by raphaelv619** [haseeb-heaven/GTLibc#2]
In my pointerscan the values ​​are as follows: GT_ReadPointerOffset (base_addr, 01F441E8) + 390;
Note: it is a green address(CheatEngine) that I want to change the value.
With that, the compiler gives me the following error:
error: invalid suffix "F441E8" on integer constant
GT_ReadPointerOffset (base_addr, 01F441E8) +390;

And the function says:
the expression must be a pointer to a complete object type

**Comment by haseeb-heaven** [comment]
For hexa-decimal values use **0x** as prefix like 0x01F441E8 and 0x390.
