### ISSUE TITLE
How to write on this address?

### ISSUE THREAD

**Issue by raphaelv619** [haseeb-heaven/GTLibc#3]
![myaddr](https://user-images.githubusercontent.com/44813959/80318885-96781700-87e3-11ea-9cd5-f46a37ec77a2.png)
This is my pointer scan result for a green address.

I am trying to make a script to modify the value of this address, see my code below:
`#include <stdio.h>
#include "GTLibc.c"

DWORD p_id = GT_NIL;
void init();
void run();

int main()
{

    char *game_name = "fifa15";
    HANDLE game_handle = GT_FindGameProcess(game_name);

    if(game_handle != NULL){
        printf("Game found %s\n", GT_GetGameName());
        p_id = GT_GetProcessID();
        init();
    }

    return 0;
}

void init()
{
    printf("p_id %u\n", p_id);
    LPBYTE base_addr = GT_GetGameBaseAddress(p_id);
    printf("base_addr %p", base_addr);
   

}

void run()
{

}`

But I'm having an error with the getGameBaseAddress function:
![reading_invalid_memory](https://user-images.githubusercontent.com/44813959/80318961-1ef6b780-87e4-11ea-93c6-6e1936af6076.jpg)

My logs:
Game found fifa15
p_id 7636
base_addr 00000000

**Comment by haseeb-heaven** [comment]
Send me full logs as i can see your base address could not be found thats the error there.
And make sure you are using **latest version** GTLibc **v1.5** as i have add support for **64-bit games** now.

And to read that value use it like this.

```
void* value_ptr =  GT_ReadPointerOffset(game_base_addr,0x01F44E18) + 0x390; //0x is important.
int value = *(int*)value_ptr; //Cast the void* to your data-type.
printf("Value is %d\n",value);
```

**Comment by gustavomaltez** [comment]
I'm having the same problem as raphaelv619, whenever I try to get the base game address the program returns me the same error as raphaelv619, in my view the problem is in the GT_GetGameBaseAddress() function, even passing directly the process id to it occurs mistake. If you have any idea how to get the base address in another way, I would be very grateful. His work in this library is incredible!

**Comment by haseeb-heaven** [comment]
> I'm having the same problem as raphaelv619, whenever I try to get the base game address the program returns me the same error as raphaelv619, in my view the problem is in the GT_GetGameBaseAddress() function, even passing directly the process id to it occurs mistake. If you have any idea how to get the base address in another way, I would be very grateful. His work in this library is incredible!

As i told before send me whole logs and details of game in which you are getting error, i have tested for both 32 and 64bit games base address works fine, you can do one thing open game in cheat engine and write game nam example "FIFA.exe" and you will get base address.
And in 32bit games base address remains same for most games i e : 0x00400000 .
Send me full logs to my e-mail : haseebmir.hm@gmail.com

**Comment by haseeb-heaven** [comment]
Ok i figured out  the problem you are trying to access base address of **64bit** game from **32bit** application(_Trainer_).
You can use gcc to build **32bit** and **64bit** trainer using these commands.

For 32 bit use : _gcc -m32 -o MyTrainer.exe MyTrainer.c_ 
For 64 bit use : _gcc -m64 -o Myrainer.exe MyTrainer.c_

You have to use **64bit** trainer for **64bit** games and **32bit** trainer for **32bit** games.

**Comment by haseeb-heaven** [comment]
Use newest version of library it has Game trainer architecture compatibility detection so it wont show you error on **GT_GetGameBaseAddress()**

And now you can do like this.

void* value_addr =  GT_ReadPointerOffset(game_base_addr,0x01F44E18) + 0x390; //0x is important.
int value = GT_Read4Bytes(value_addr);
printf("Value is %d\n",value);

**Comment by haseeb-heaven** [comment]
> I'm having the same problem as raphaelv619, whenever I try to get the base game address the program returns me the same error as raphaelv619, in my view the problem is in the GT_GetGameBaseAddress() function, even passing directly the process id to it occurs mistake. If you have any idea how to get the base address in another way, I would be very grateful. His work in this library is incredible!

Use newest version of library it has Game trainer architecture compatibility detection so it wont show you error on GT_GetGameBaseAddress()
